### ISSUE TITLE
High-quality stylus-compatible touchscreen with mainline Linux support

### ISSUE THREAD

**Issue by raj-magesh** [whatthefilament/Framework-Tablet#1]
Hey, do you have any recs for an excellent touchscreen with stylus support (i.e. low input lag, pressure sensitivity, ergonomic, decent resolution) that also has Linux drivers in the mainline kernel?

Thanks for the cool project: really excited to see where it goes!

**Comment by lrlucchini** [comment]
Are the ports for displays pretty standard? Could i in theory find a better screen on Amazon that works with the motherboard port?

**Comment by whatthefilament** [comment]
@lrlucchini The motherboard has an EDP port that it uses for the factory monitor. If you can find a touchscreen monitor that uses an EDP port you could certainly find a better screen. To make it easier to obtain parts, i based this design around a stock external display you'd use with any computer. With the step files, you can modify the bezel to accept any monitor you'd like. I suggest finding one that does power, data, and touch-over USB to keep wiring simple.
