### ISSUE TITLE
CC-BY-SA 4.0 licence for image files?

### ISSUE THREAD

**Issue by junaruga** [whatthefilament/Framework-Tablet#2]
Hello,

Thanks for creating this amazing project!
I am an editor of the [Framework's Wikipedia page](https://en.wikipedia.org/wiki/Framework_Computer). And I want to upload [this photo file](https://github.com/whatthefilament/Framework-Tablet/blob/main/Images/Assembly%20Instruction%20Manual%20Pictures/Originals/IMG_0046.JPG) on this repository, to the Wikipedia page as a case of an individually driven project.

I can upload it by myself via [Upload Wizard](https://commons.wikimedia.org/wiki/Special:UploadWizard). However, it seems that Wikipedia (the wizard) only allows the licenses below in the following screenshot. And the "CC-BY-SA 4.0" is the default.

![screenshot-commons wikimedia org-upload_wizard-license](https://user-images.githubusercontent.com/121989/183267466-158c917c-0560-49ee-8884-8d681d123eb3.png)

So I have a suggestion. Could you adjust the license info of this repository for image files to have the CC-BY-SA 4.0 license or other CC licenses on the list?

Here are some projects of doing this for your reference.

* https://source.mnt.re/reform/pocket-reform/-/blob/main/README.md
  > Other documentation, artwork, photos and drawings that are not trademarks (see below): [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode)
* https://github.com/penk/MainboardTerminal/blob/master/README.md#copyright-and-license
* https://github.com/brickbots/framedeck/blob/main/README.md#copyright-and-license

Thanks!

**Comment by whatthefilament** [comment]
Hey @junaruga, I don't think they let you adjust the license for a repository after you make the initial commit. 

I am happy to send an email permitting as outlined in the screenshot of the wizard.

**Comment by whatthefilament** [comment]
@junaruga are there any specific files you want to use? It looks like  I can go into the wizard and upload them myself and grant permission

**Comment by whatthefilament** [comment]
Picture 1:

[[File:Framework Tablet Overview.jpg|thumb|Framework Tablet Overview]]
https://commons.wikimedia.org/wiki/File:Framework_Tablet_Overview.jpg

Picture 2:

[[File:Framework Tablet Internals.jpg|thumb|Framework Tablet Internals]]
https://commons.wikimedia.org/wiki/File:Framework_Tablet_Internals.jpg

Picture 3: 

[[File:Framework Tablet Complete Build.jpg|thumb|Framework Tablet Complete Build]]
https://commons.wikimedia.org/wiki/File:Framework_Tablet_Complete_Build.jpg

Picture 4:

[[File:Framework Tablet Complete Build Back.jpg|thumb|Framework Tablet Complete Build Back]]
https://commons.wikimedia.org/wiki/File:Framework_Tablet_Complete_Build_Back.jpg

**Comment by junaruga** [comment]
Thanks for your help! Yeah, I wanted to see the Picture 3 (`Originals/IMG_0046.JPG`) to be uploaded.

**Comment by junaruga** [comment]
I added your photo to the page: https://en.wikipedia.org/wiki/Framework_Computer now!

By the way, I just want to share one tip that might be a tip for an uploaded photo to be kept, not to be deleted on Wikipedia. In the past, I saw a person upload his artwork (wallpaper) image to Wikimedia. Then after days or months, it was deleted by Wikipedia. I don't know why.

When I upload a 3rd person's photo, I added the Summary - Source item as the original photo URL just in case. So far all the photos I uploaded by myself are not deleted on Wikipedia.
E.g. https://commons.wikimedia.org/wiki/File:Mainboard-terminal-heroshot.jpg

**Comment by whatthefilament** [comment]
Awesome! Thanks for the highlight!

**Comment by junaruga** [comment]
Yeah, possibly the current photo is okay. In the past, I uploaded my Framework Laptop photos as own work without the Summary - Source item and the link. And those are still kept there :)

* https://commons.wikimedia.org/wiki/File:Framework_laptop_part_made_with_love_by_team.jpg
* https://commons.wikimedia.org/wiki/File:Framework_laptop_sway_community_forum_small.png

**Comment by whatthefilament** [comment]
Just looking at your posts. Jealous your able to get a fair phone. Wish they sold them in the US

**Comment by junaruga** [comment]
Yeah, I am using Fairphone 3, and I am happy with it. The metadata in the first link shows the info. It was easy to buy it as I live in the Czech Republic. :)
